### ISSUE TITLE
how to export the output of getColoredPathway?

### ISSUE THREAD

**Issue by duleise** [egonw/old-rWikiPathways#6]
according to the example
`writeLines(svg, "pathway.svg")` is the way to export the image file.
somehow it does not work on my machine. i also tried other image format.
i managed to do to using [rsvg](https://github.com/jeroen/rsvg) 
i wonder if anybody met this issue as well?

**Comment by duleise** [comment]
to use the same example in the help file, this seems work.

```
svg = getColoredPathway(pathway = "WP554",  graphId = c("ef1f3","e68e0"), color=c("FF0000", "0000FF"), fileType = "svg")
rsvg::rsvg_pdf("ppp.svg","out.pdf")

```

**Comment by egonw** [comment]
This method was using the webservice, but that was causing trouble on the service and was deprecated. Please see https://bioconductor.org/packages/release/bioc/vignettes/rWikiPathways/inst/doc/Pathway-Analysis.html for the current approach.
